# Credits to ScanNet 200 dataset
# https://github.com/ScanNet/ScanNet/tree/master/BenchmarkScripts/ScanNet200

CLASS_LABELS_200 =(
    'shower head',
    'spray',
    'inhaler',
    'guitar case',
    'plunger',
    'range hood',
    'toilet paper dispenser',
    'adapter',
    'soy sauce',
    'pipe',
    'bottle',
    'door',
    'scale',
    'paper towel',
    'paper towel roll',
    'stove',
    'mailbox',
    'scissors',
    'tape',
    'bathroom stall',
    'chopsticks',
    'case of water bottles',
    'hand sanitizer',
    'laptop',
    'alcohol disinfection',
    'keyboard',
    'coffee maker',
    'light',
    'toaster',
    'stuffed animal',
    'divider',
    'clothes dryer',
    'toilet seat cover dispenser',
    'file cabinet',
    'curtain',
    'ironing board',
    'fire extinguisher',
    'fruit',
    'object',
    'blinds',
    'container',
    'bag',
    'oven',
    'body wash',
    'bucket',
    'cd case',
    'tv',
    'tray',
    'bowl',
    'cabinet',
    'speaker',
    'crate',
    'projector',
    'book',
    'school bag',
    'laundry detergent',
    'mattress',
    'bathtub',
    'clothes',
    'candle',
    'basket',
    'glass',
    'face wash',
    'notebook',
    'purse',
    'shower',
    'power outlet',
    'trash bin',
    'paper bag',
    'water dispenser',
    'package',
    'bulletin board',
    'printer',
    'windowsill',
    'disinfecting wipes',
    'bookshelf',
    'recycling bin',
    'headphones',
    'dresser',
    'mouse',
    'shower gel',
    'dustpan',
    'cup',
    'storage organizer',
    'vacuum cleaner',
    'fireplace',
    'dish rack',
    'coffee kettle',
    'fire alarm',
    'plants',
    'rag',
    'can',
    'piano',
    'bathroom cabinet',
    'shelf',
    'cushion',
    'monitor',
    'fan',
    'tube',
    'box',
    'blackboard',
    'ball',
    'bicycle',
    'guitar',
    'trash can',
    'hand sanitizers',
    'paper towel dispenser',
    'whiteboard',
    'bin',
    'potted plant',
    'tennis',
    'soap dish',
    'structure',
    'calendar',
    'dumbbell',
    'fish oil',
    'paper cutter',
    'ottoman',
    'stool',
    'hand wash',
    'lamp',
    'toaster oven',
    'music stand',
    'water bottle',
    'clock',
    'charger',
    'picture',
    'bascketball',
    'sink',
    'microwave',
    'screwdriver',
    'kitchen counter',
    'rack',
    'apple',
    'washing machine',
    'suitcase',
    'ladder',
    'ping pong ball',
    'window',
    'dishwasher',
    'storage container',
    'toilet paper holder',
    'coat rack',
    'soap dispenser',
    'refrigerator',
    'banana',
    'counter',
    'toilet paper',
    'mug',
    'marker pen',
    'hat',
    'aerosol',
    'luggage',
    'poster',
    'bed',
    'cart',
    'light switch',
    'backpack',
    'power strip',
    'baseball',
    'mustard',
    'bathroom vanity',
    'water pitcher',
    'closet',
    'couch',
    'beverage',
    'toy',
    'salt',
    'plant',
    'pillow',
    'broom',
    'pepper',
    'muffins',
    'multivitamin',
    'towel',
    'storage bin',
    'nightstand',
    'radiator',
    'telephone',
    'pillar',
    'tissue box',
    'vent',
    'hair dryer',
    'ledge',
    'mirror',
    'sign',
    'plate',
    'tripod',
    'chair',
    'kitchen cabinet',
    'column',
    'water cooler',
    'plastic bag',
    'umbrella',
    'doorframe',
    'paper',
    'laundry hamper',
    'food',
    'jacket',
    'closet door',
    'computer tower',
    'stairs',
    'keyboard piano',
    'person',
    'table',
    'machine',
    'projector screen',
    'shoe',
)